-- Confirmed vendor SELL prices (what a vendor pays YOU for the item),
-- as opposed to data_vendorprices.lua (what a vendor CHARGES to buy
-- something from them) -- these are different values for the same real
-- item and must not be confused with each other.
--
-- Collected directly by the user via octowow.st, item by item, across
-- several rounds, replacing the old GetVendorSellPrice/aux-itemId
-- mechanism entirely (see DEVNOTES for the Rough Gemstone Cluster bug
-- this replaced). A price of 0 means confirmed NOT sellable to any
-- vendor at all (e.g. quest items) -- this is a real, deliberate value,
-- not a placeholder or missing-data marker. An item simply absent from
-- this table has an unverified sell price and must be treated as
-- unknown (nil), never assumed or guessed.
--
-- 856 entries as of v2.1.28 -- full coverage of every non-excluded
-- recipe across all 7 sellback-eligible professions. Greenskeeper and
-- Refined Dwarven Necklace are the only two gaps, both excluded=true in
-- their data files (never a route step), so deliberately never priced.
CraftRoute_VendorSellPrices = {}
CraftRoute_VendorSellPrices["accurate scope"] = 1200
CraftRoute_VendorSellPrices["advanced target dummy"] = 2500
CraftRoute_VendorSellPrices["agatestone crown"] = 788
CraftRoute_VendorSellPrices["alluring citrine choker"] = 2749
CraftRoute_VendorSellPrices["amber orb"] = 418
CraftRoute_VendorSellPrices["amber ring"] = 149
CraftRoute_VendorSellPrices["ambersap glazed boar ribs"] = 300
CraftRoute_VendorSellPrices["amberstone pendant"] = 206
CraftRoute_VendorSellPrices["aquadynamic fish attractor"] = 62
CraftRoute_VendorSellPrices["aquamarine pendant"] = 9500
CraftRoute_VendorSellPrices["arcane elixir"] = 400
CraftRoute_VendorSellPrices["arcanite skeleton key"] = 625
CraftRoute_VendorSellPrices["arclight spanner"] = 144
CraftRoute_VendorSellPrices["argent boots"] = 12941
CraftRoute_VendorSellPrices["augerer's boots"] = 3681
CraftRoute_VendorSellPrices["augerer's gloves"] = 2271
CraftRoute_VendorSellPrices["augerer's hat"] = 4107
CraftRoute_VendorSellPrices["augerer's mantle"] = 2734
CraftRoute_VendorSellPrices["augerer's robe"] = 6213
CraftRoute_VendorSellPrices["augerer's trousers"] = 5012
CraftRoute_VendorSellPrices["azure ring"] = 158
CraftRoute_VendorSellPrices["azure shoulders"] = 2791
CraftRoute_VendorSellPrices["azure silk belt"] = 1488
CraftRoute_VendorSellPrices["azure silk cloak"] = 2240
CraftRoute_VendorSellPrices["azure silk hood"] = 1244
CraftRoute_VendorSellPrices["azure silk pants"] = 1494
CraftRoute_VendorSellPrices["azure silk vest"] = 1874
CraftRoute_VendorSellPrices["baked salmon"] = 10
CraftRoute_VendorSellPrices["barbaric gloves"] = 1071
CraftRoute_VendorSellPrices["barbaric harness"] = 4935
CraftRoute_VendorSellPrices["barbaric iron boots"] = 3700
CraftRoute_VendorSellPrices["barbaric iron breastplate"] = 3330
CraftRoute_VendorSellPrices["barbaric iron gloves"] = 2711
CraftRoute_VendorSellPrices["barbaric iron helm"] = 3337
CraftRoute_VendorSellPrices["barbaric iron shoulders"] = 2500
CraftRoute_VendorSellPrices["barbaric leggings"] = 3151
CraftRoute_VendorSellPrices["barbaric shoulders"] = 2609
CraftRoute_VendorSellPrices["barbecued buzzard wing"] = 300
CraftRoute_VendorSellPrices["big bear steak"] = 125
CraftRoute_VendorSellPrices["big black mace"] = 17291
CraftRoute_VendorSellPrices["big bronze bomb"] = 500
CraftRoute_VendorSellPrices["big bronze knife"] = 1426
CraftRoute_VendorSellPrices["big iron bomb"] = 750
CraftRoute_VendorSellPrices["big voodoo mask"] = 5350
CraftRoute_VendorSellPrices["big voodoo robe"] = 7275
CraftRoute_VendorSellPrices["binding signet"] = 751
CraftRoute_VendorSellPrices["black mageweave boots"] = 5459
CraftRoute_VendorSellPrices["black mageweave gloves"] = 2859
CraftRoute_VendorSellPrices["black mageweave headband"] = 5421
CraftRoute_VendorSellPrices["black mageweave robe"] = 5257
CraftRoute_VendorSellPrices["black mageweave shoulders"] = 5479
CraftRoute_VendorSellPrices["black mageweave vest"] = 4815
CraftRoute_VendorSellPrices["black silk pack"] = 4000
CraftRoute_VendorSellPrices["black whelp cloak"] = 519
CraftRoute_VendorSellPrices["blackmouth oil"] = 10
CraftRoute_VendorSellPrices["blackrock ironclamps"] = 625
CraftRoute_VendorSellPrices["bloodstone warblade"] = 27106
CraftRoute_VendorSellPrices["blue firework"] = 1
CraftRoute_VendorSellPrices["blue glittering axe"] = 14659
CraftRoute_VendorSellPrices["blue linen robe"] = 243
CraftRoute_VendorSellPrices["blue linen shirt"] = 75
CraftRoute_VendorSellPrices["blue overalls"] = 589
CraftRoute_VendorSellPrices["blue rocket cluster"] = 25
CraftRoute_VendorSellPrices["blue starfire"] = 3250
CraftRoute_VendorSellPrices["boiled clams"] = 20
CraftRoute_VendorSellPrices["bolt of linen cloth"] = 40
CraftRoute_VendorSellPrices["bolt of mageweave"] = 1250
CraftRoute_VendorSellPrices["bolt of runecloth"] = 2000
CraftRoute_VendorSellPrices["bolt of silk cloth"] = 600
CraftRoute_VendorSellPrices["bolt of woolen cloth"] = 100
CraftRoute_VendorSellPrices["boots of the enchanter"] = 2272
CraftRoute_VendorSellPrices["bright copper necklace"] = 108
CraftRoute_VendorSellPrices["bright copper ring"] = 92
CraftRoute_VendorSellPrices["bright yellow shirt"] = 500
CraftRoute_VendorSellPrices["bright-eye goggles"] = 2105
CraftRoute_VendorSellPrices["brightcloth cloak"] = 9716
CraftRoute_VendorSellPrices["brightcloth pants"] = 15484
CraftRoute_VendorSellPrices["brilliant opal gemstone"] = 7000
CraftRoute_VendorSellPrices["brilliant smallfish"] = 1
CraftRoute_VendorSellPrices["bristle whisker catfish"] = 4
CraftRoute_VendorSellPrices["bronze axe"] = 1269
CraftRoute_VendorSellPrices["bronze battle axe"] = 2435
CraftRoute_VendorSellPrices["bronze bruiser"] = 2752
CraftRoute_VendorSellPrices["bronze cuffed bangles"] = 188
CraftRoute_VendorSellPrices["bronze framework"] = 600
CraftRoute_VendorSellPrices["bronze greatsword"] = 2205
CraftRoute_VendorSellPrices["bronze mace"] = 1119
CraftRoute_VendorSellPrices["bronze scepter"] = 689
CraftRoute_VendorSellPrices["bronze shortsword"] = 1439
CraftRoute_VendorSellPrices["bronze tube"] = 200
CraftRoute_VendorSellPrices["bronze warhammer"] = 1944
CraftRoute_VendorSellPrices["brown linen pants"] = 60
CraftRoute_VendorSellPrices["brown linen shirt"] = 11
CraftRoute_VendorSellPrices["brown linen vest"] = 31
CraftRoute_VendorSellPrices["bulky copper ring"] = 92
CraftRoute_VendorSellPrices["burning star gemstone"] = 1000
CraftRoute_VendorSellPrices["carrion surprise"] = 300
CraftRoute_VendorSellPrices["catseye elixir"] = 150
CraftRoute_VendorSellPrices["catseye ultra goggles"] = 4398
CraftRoute_VendorSellPrices["centaur hoof circlet"] = 550
CraftRoute_VendorSellPrices["cindercloth boots"] = 6765
CraftRoute_VendorSellPrices["cindercloth cloak"] = 9503
CraftRoute_VendorSellPrices["cindercloth gloves"] = 5955
CraftRoute_VendorSellPrices["cindercloth robe"] = 6644
CraftRoute_VendorSellPrices["cindercloth vest"] = 10561
CraftRoute_VendorSellPrices["cinderfall band"] = 13875
CraftRoute_VendorSellPrices["circlet of dampening"] = 1382
CraftRoute_VendorSellPrices["clam chowder"] = 75
CraftRoute_VendorSellPrices["coarse blasting powder"] = 12
CraftRoute_VendorSellPrices["coarse dynamite"] = 75
CraftRoute_VendorSellPrices["coarse gemstone cluster"] = 40
CraftRoute_VendorSellPrices["coarse grinding stone"] = 10
CraftRoute_VendorSellPrices["coarse gritted paper"] = 10
CraftRoute_VendorSellPrices["coarse sharpening stone"] = 10
CraftRoute_VendorSellPrices["coarse weightstone"] = 10
CraftRoute_VendorSellPrices["colorful kilt"] = 935
CraftRoute_VendorSellPrices["comfortable leather hat"] = 4131
CraftRoute_VendorSellPrices["compact harvest reaper kit"] = 4000
CraftRoute_VendorSellPrices["cooked crab claw"] = 25
CraftRoute_VendorSellPrices["cooked glossy mightfish"] = 8
CraftRoute_VendorSellPrices["copper axe"] = 109
CraftRoute_VendorSellPrices["copper bangle"] = 9
CraftRoute_VendorSellPrices["copper battle axe"] = 613
CraftRoute_VendorSellPrices["copper bracers"] = 17
CraftRoute_VendorSellPrices["copper chain belt"] = 56
CraftRoute_VendorSellPrices["copper chain boots"] = 49
CraftRoute_VendorSellPrices["copper chain pants"] = 67
CraftRoute_VendorSellPrices["copper chain vest"] = 142
CraftRoute_VendorSellPrices["copper claymore"] = 241
CraftRoute_VendorSellPrices["copper dagger"] = 194
CraftRoute_VendorSellPrices["copper mace"] = 106
CraftRoute_VendorSellPrices["copper modulator"] = 50
CraftRoute_VendorSellPrices["copper shortsword"] = 110
CraftRoute_VendorSellPrices["copper staff"] = 214
CraftRoute_VendorSellPrices["copper tube"] = 120
CraftRoute_VendorSellPrices["coyote steak"] = 20
CraftRoute_VendorSellPrices["crafted heavy shot"] = 0
CraftRoute_VendorSellPrices["crafted light shot"] = 0
CraftRoute_VendorSellPrices["crafted solid shot"] = 0
CraftRoute_VendorSellPrices["craftsmans monocle"] = 3172
CraftRoute_VendorSellPrices["crawford apple tarte"] = 300
CraftRoute_VendorSellPrices["crimson silk cloak"] = 2314
CraftRoute_VendorSellPrices["crimson silk gloves"] = 2569
CraftRoute_VendorSellPrices["crimson silk pantaloons"] = 3899
CraftRoute_VendorSellPrices["crimson silk shoulders"] = 2781
CraftRoute_VendorSellPrices["crimson silk vest"] = 3329
CraftRoute_VendorSellPrices["crown of elegance"] = 7058
CraftRoute_VendorSellPrices["crude scope"] = 125
CraftRoute_VendorSellPrices["crystal earring"] = 2048
CraftRoute_VendorSellPrices["crystalfire armlets"] = 7175
CraftRoute_VendorSellPrices["crystalweft bracers"] = 2500
CraftRoute_VendorSellPrices["cured heavy hide"] = 225
CraftRoute_VendorSellPrices["cured light hide"] = 110
CraftRoute_VendorSellPrices["cured medium hide"] = 200
CraftRoute_VendorSellPrices["cured rugged hide"] = 500
CraftRoute_VendorSellPrices["cured thick hide"] = 500
CraftRoute_VendorSellPrices["curiously tasty omelet"] = 150
CraftRoute_VendorSellPrices["dark iron bomb"] = 1250
CraftRoute_VendorSellPrices["dark iron rifle"] = 29152
CraftRoute_VendorSellPrices["dark iron shoulders"] = 10776
CraftRoute_VendorSellPrices["dark iron signet ring"] = 21508
CraftRoute_VendorSellPrices["dark leather boots"] = 547
CraftRoute_VendorSellPrices["dark leather cloak"] = 561
CraftRoute_VendorSellPrices["dark leather gloves"] = 791
CraftRoute_VendorSellPrices["dark leather pants"] = 1089
CraftRoute_VendorSellPrices["dark leather shoulders"] = 1457
CraftRoute_VendorSellPrices["dark leather tunic"] = 689
CraftRoute_VendorSellPrices["dark silk shirt"] = 1200
CraftRoute_VendorSellPrices["dawnbright cuffs"] = 642
CraftRoute_VendorSellPrices["dazzling aquamarine loop"] = 1945
CraftRoute_VendorSellPrices["dazzling mithril rapier"] = 20092
CraftRoute_VendorSellPrices["dazzling moonstone band"] = 400
CraftRoute_VendorSellPrices["deadly blunderbuss"] = 1179
CraftRoute_VendorSellPrices["deadly bronze poniard"] = 2731
CraftRoute_VendorSellPrices["deadly scope"] = 1500
CraftRoute_VendorSellPrices["deepdive helmet"] = 5227
CraftRoute_VendorSellPrices["deepmist choker"] = 206
CraftRoute_VendorSellPrices["delicate arcanite converter"] = 10000
CraftRoute_VendorSellPrices["delicate mithril amulet"] = 2499
CraftRoute_VendorSellPrices["dense blasting powder"] = 250
CraftRoute_VendorSellPrices["dense dynamite"] = 500
CraftRoute_VendorSellPrices["dense gemstone cluster"] = 160
CraftRoute_VendorSellPrices["dense grinding stone"] = 200
CraftRoute_VendorSellPrices["dense gritted paper"] = 300
CraftRoute_VendorSellPrices["dense sharpening stone"] = 75
CraftRoute_VendorSellPrices["dense weightstone"] = 75
CraftRoute_VendorSellPrices["deviate scale gloves"] = 420
CraftRoute_VendorSellPrices["discolored healing potion"] = 25
CraftRoute_VendorSellPrices["discombobulator ray"] = 1000
CraftRoute_VendorSellPrices["diviner's boots"] = 4972
CraftRoute_VendorSellPrices["diviner's cowl"] = 4731
CraftRoute_VendorSellPrices["diviner's epaulets"] = 6034
CraftRoute_VendorSellPrices["diviner's mitts"] = 3271
CraftRoute_VendorSellPrices["diviner's pantaloons"] = 7638
CraftRoute_VendorSellPrices["diviner's robe"] = 9408
CraftRoute_VendorSellPrices["double-stitched woolen shoulders"] = 331
CraftRoute_VendorSellPrices["draenethyst baton"] = 4308
CraftRoute_VendorSellPrices["dragonbreath chili"] = 300
CraftRoute_VendorSellPrices["dreamless sleep potion"] = 250
CraftRoute_VendorSellPrices["dreamweave gloves"] = 3944
CraftRoute_VendorSellPrices["dreamweave vest"] = 7946
CraftRoute_VendorSellPrices["dreary opal gemstone"] = 4000
CraftRoute_VendorSellPrices["dry pork ribs"] = 25
CraftRoute_VendorSellPrices["dusky belt"] = 2587
CraftRoute_VendorSellPrices["dusky boots"] = 4237
CraftRoute_VendorSellPrices["dusky leather armor"] = 3760
CraftRoute_VendorSellPrices["dusky leather leggings"] = 3097
CraftRoute_VendorSellPrices["earthen leather shoulders"] = 1306
CraftRoute_VendorSellPrices["earthen vest"] = 2696
CraftRoute_VendorSellPrices["earthrock loop"] = 354
CraftRoute_VendorSellPrices["ebon ring"] = 250
CraftRoute_VendorSellPrices["ebon shiv"] = 24892
CraftRoute_VendorSellPrices["edge of winter"] = 9178
CraftRoute_VendorSellPrices["elaborate golden bracelets"] = 2481
CraftRoute_VendorSellPrices["elegant emerald gemstone"] = 10000
CraftRoute_VendorSellPrices["elixir of agility"] = 200
CraftRoute_VendorSellPrices["elixir of defense"] = 40
CraftRoute_VendorSellPrices["elixir of demonslaying"] = 700
CraftRoute_VendorSellPrices["elixir of detect demon"] = 500
CraftRoute_VendorSellPrices["elixir of detect lesser invisibility"] = 150
CraftRoute_VendorSellPrices["elixir of detect undead"] = 300
CraftRoute_VendorSellPrices["elixir of dream vision"] = 600
CraftRoute_VendorSellPrices["elixir of firepower"] = 35
CraftRoute_VendorSellPrices["elixir of fortitude"] = 110
CraftRoute_VendorSellPrices["elixir of frost power"] = 35
CraftRoute_VendorSellPrices["elixir of giant growth"] = 95
CraftRoute_VendorSellPrices["elixir of giants"] = 700
CraftRoute_VendorSellPrices["elixir of greater agility"] = 600
CraftRoute_VendorSellPrices["elixir of greater defense"] = 200
CraftRoute_VendorSellPrices["elixir of greater firepower"] = 35
CraftRoute_VendorSellPrices["elixir of greater intellect"] = 1000
CraftRoute_VendorSellPrices["elixir of greater water breathing"] = 250
CraftRoute_VendorSellPrices["elixir of lesser agility"] = 35
CraftRoute_VendorSellPrices["elixir of lion's strength"] = 20
CraftRoute_VendorSellPrices["elixir of minor agility"] = 15
CraftRoute_VendorSellPrices["elixir of minor defense"] = 5
CraftRoute_VendorSellPrices["elixir of minor fortitude"] = 15
CraftRoute_VendorSellPrices["elixir of ogre's strength"] = 20
CraftRoute_VendorSellPrices["elixir of poison resistance"] = 35
CraftRoute_VendorSellPrices["elixir of rapid growth"] = 0
CraftRoute_VendorSellPrices["elixir of shadow power"] = 35
CraftRoute_VendorSellPrices["elixir of superior defense"] = 500
CraftRoute_VendorSellPrices["elixir of the mongoose"] = 1250
CraftRoute_VendorSellPrices["elixir of water breathing"] = 95
CraftRoute_VendorSellPrices["elixir of wisdom"] = 100
CraftRoute_VendorSellPrices["emberstone idol"] = 3845
CraftRoute_VendorSellPrices["emberstone studded ring"] = 2671
CraftRoute_VendorSellPrices["embossed leather boots"] = 268
CraftRoute_VendorSellPrices["embossed leather cloak"] = 112
CraftRoute_VendorSellPrices["embossed leather gloves"] = 71
CraftRoute_VendorSellPrices["embossed leather pants"] = 347
CraftRoute_VendorSellPrices["embossed leather vest"] = 192
CraftRoute_VendorSellPrices["enchanted bracelets"] = 612
CraftRoute_VendorSellPrices["enchanted mageweave pouch"] = 2500
CraftRoute_VendorSellPrices["enchanted runecloth bag"] = 10000
CraftRoute_VendorSellPrices["encrusted bronze staff"] = 1587
CraftRoute_VendorSellPrices["encrusted copper bangle"] = 124
CraftRoute_VendorSellPrices["ethereal frostspark crown"] = 11000
CraftRoute_VendorSellPrices["explosive sheep"] = 1000
CraftRoute_VendorSellPrices["ez-thro dynamite ii"] = 200
CraftRoute_VendorSellPrices["ez-thro dynamite"] = 75
CraftRoute_VendorSellPrices["facetted moonstone brooch"] = 3050
CraftRoute_VendorSellPrices["fangclaw relic"] = 450
CraftRoute_VendorSellPrices["farraki ceremony totem"] = 1750
CraftRoute_VendorSellPrices["felcloth hood"] = 10775
CraftRoute_VendorSellPrices["filet of redgill"] = 5
CraftRoute_VendorSellPrices["fine leather belt"] = 193
CraftRoute_VendorSellPrices["fine leather boots"] = 385
CraftRoute_VendorSellPrices["fine leather cloak"] = 267
CraftRoute_VendorSellPrices["fine leather gloves"] = 181
CraftRoute_VendorSellPrices["fine leather pants"] = 829
CraftRoute_VendorSellPrices["fire goggles"] = 3478
CraftRoute_VendorSellPrices["fire oil"] = 12
CraftRoute_VendorSellPrices["firework launcher"] = 0
CraftRoute_VendorSellPrices["flame deflector"] = 200
CraftRoute_VendorSellPrices["flash bomb"] = 300
CraftRoute_VendorSellPrices["flying tiger goggles"] = 408
CraftRoute_VendorSellPrices["formal white shirt"] = 550
CraftRoute_VendorSellPrices["free action potion"] = 75
CraftRoute_VendorSellPrices["frost leather cloak"] = 2269
CraftRoute_VendorSellPrices["frost protection potion"] = 300
CraftRoute_VendorSellPrices["frost tiger blade"] = 14120
CraftRoute_VendorSellPrices["frostweave gloves"] = 5471
CraftRoute_VendorSellPrices["frostweave robe"] = 9665
CraftRoute_VendorSellPrices["frostweave tunic"] = 9702
CraftRoute_VendorSellPrices["gem encrusted choker"] = 2149
CraftRoute_VendorSellPrices["gem-studded leather belt"] = 2652
CraftRoute_VendorSellPrices["gemmed citrine pendant"] = 6500
CraftRoute_VendorSellPrices["gemmed copper gauntlets"] = 216
CraftRoute_VendorSellPrices["gemstone compendium"] = 19500
CraftRoute_VendorSellPrices["ghost dye"] = 750
CraftRoute_VendorSellPrices["ghostweave belt"] = 5763
CraftRoute_VendorSellPrices["ghostweave gloves"] = 6087
CraftRoute_VendorSellPrices["giant clam scorcho"] = 312
CraftRoute_VendorSellPrices["gift of arthas"] = 250
CraftRoute_VendorSellPrices["gilneas hot stew"] = 300
CraftRoute_VendorSellPrices["girdle of insight"] = 14126
CraftRoute_VendorSellPrices["girdle of the dawn"] = 9365
CraftRoute_VendorSellPrices["gleaming chain"] = 245
CraftRoute_VendorSellPrices["gleaming jade gemstone"] = 700
CraftRoute_VendorSellPrices["gleaming silver necklace"] = 509
CraftRoute_VendorSellPrices["glinting steel dagger"] = 8072
CraftRoute_VendorSellPrices["gloomweed bindings"] = 200
CraftRoute_VendorSellPrices["gloomy diamond gemstone"] = 2000
CraftRoute_VendorSellPrices["gloves of meditation"] = 610
CraftRoute_VendorSellPrices["gloves of the greatfather"] = 2268
CraftRoute_VendorSellPrices["glyph codex"] = 6250
CraftRoute_VendorSellPrices["gnomish universal remote"] = 500
CraftRoute_VendorSellPrices["goblin deviled clams"] = 95
CraftRoute_VendorSellPrices["goblin land mine"] = 1600
CraftRoute_VendorSellPrices["goblin radio kaboom-box"] = 0
CraftRoute_VendorSellPrices["goblin rocket fuel"] = 250
CraftRoute_VendorSellPrices["gold bar"] = 600
CraftRoute_VendorSellPrices["gold power core"] = 250
CraftRoute_VendorSellPrices["goldcrest amulet"] = 2251
CraftRoute_VendorSellPrices["golden iron destroyer"] = 8360
CraftRoute_VendorSellPrices["golden jade ring"] = 7169
CraftRoute_VendorSellPrices["golden rod"] = 500
CraftRoute_VendorSellPrices["golden scale bracers"] = 2497
CraftRoute_VendorSellPrices["golden scale coif"] = 4405
CraftRoute_VendorSellPrices["golden scale cuirass"] = 6558
CraftRoute_VendorSellPrices["golden scale leggings"] = 3882
CraftRoute_VendorSellPrices["golden scale shoulders"] = 3106
CraftRoute_VendorSellPrices["golden skeleton key"] = 300
CraftRoute_VendorSellPrices["goldenshade quartz crown"] = 3000
CraftRoute_VendorSellPrices["goldfire crystal bracelet"] = 1500
CraftRoute_VendorSellPrices["graceful agate gemstone"] = 500
CraftRoute_VendorSellPrices["gray woolen robe"] = 638
CraftRoute_VendorSellPrices["gray woolen shirt"] = 200
CraftRoute_VendorSellPrices["great rage potion"] = 150
CraftRoute_VendorSellPrices["greater arcane elixir"] = 750
CraftRoute_VendorSellPrices["greater arcane protection potion"] = 750
CraftRoute_VendorSellPrices["greater binding signet"] = 2177
CraftRoute_VendorSellPrices["greater dreamless sleep potion"] = 1000
CraftRoute_VendorSellPrices["greater frost protection potion"] = 750
CraftRoute_VendorSellPrices["greater healing potion"] = 125
CraftRoute_VendorSellPrices["greater holy protection potion"] = 750
CraftRoute_VendorSellPrices["greater mana potion"] = 120
CraftRoute_VendorSellPrices["greater nature protection potion"] = 750
CraftRoute_VendorSellPrices["greater shadow protection potion"] = 100
CraftRoute_VendorSellPrices["greater stoneshield potion"] = 750
CraftRoute_VendorSellPrices["green firework"] = 0
CraftRoute_VendorSellPrices["green holiday shirt"] = 750
CraftRoute_VendorSellPrices["green iron boots"] = 1767
CraftRoute_VendorSellPrices["green iron bracers"] = 1771
CraftRoute_VendorSellPrices["green iron gauntlets"] = 1295
CraftRoute_VendorSellPrices["green iron hauberk"] = 5658
CraftRoute_VendorSellPrices["green iron helm"] = 3053
CraftRoute_VendorSellPrices["green iron leggings"] = 2906
CraftRoute_VendorSellPrices["green iron shoulders"] = 2571
CraftRoute_VendorSellPrices["green leather armor"] = 2366
CraftRoute_VendorSellPrices["green leather belt"] = 1311
CraftRoute_VendorSellPrices["green leather bracers"] = 1934
CraftRoute_VendorSellPrices["green linen bracers"] = 45
CraftRoute_VendorSellPrices["green linen shirt"] = 37
CraftRoute_VendorSellPrices["green rocket cluster"] = 25
CraftRoute_VendorSellPrices["green silk armor"] = 2398
CraftRoute_VendorSellPrices["green silk pack"] = 3000
CraftRoute_VendorSellPrices["green silken shoulders"] = 2323
CraftRoute_VendorSellPrices["green tinted goggles"] = 1410
CraftRoute_VendorSellPrices["green whelp armor"] = 3773
CraftRoute_VendorSellPrices["green woolen bag"] = 450
CraftRoute_VendorSellPrices["green woolen vest"] = 358
CraftRoute_VendorSellPrices["grilled squid"] = 8
CraftRoute_VendorSellPrices["guardian armor"] = 3477
CraftRoute_VendorSellPrices["guardian belt"] = 2055
CraftRoute_VendorSellPrices["guardian cloak"] = 2536
CraftRoute_VendorSellPrices["guardian gloves"] = 2299
CraftRoute_VendorSellPrices["guardian pants"] = 2794
CraftRoute_VendorSellPrices["gyrochronatom"] = 750
CraftRoute_VendorSellPrices["gyrofreeze ice reflector"] = 12500
CraftRoute_VendorSellPrices["gyromatic micro-adjustor"] = 16
CraftRoute_VendorSellPrices["handful of copper bolts"] = 12
CraftRoute_VendorSellPrices["handstitched leather belt"] = 34
CraftRoute_VendorSellPrices["handstitched leather boots"] = 29
CraftRoute_VendorSellPrices["handstitched leather bracers"] = 28
CraftRoute_VendorSellPrices["handstitched leather cloak"] = 34
CraftRoute_VendorSellPrices["handstitched leather pants"] = 71
CraftRoute_VendorSellPrices["handstitched leather vest"] = 40
CraftRoute_VendorSellPrices["handstitched linen britches"] = 226
CraftRoute_VendorSellPrices["hardened iron shortsword"] = 5468
CraftRoute_VendorSellPrices["harpy talon ring"] = 500
CraftRoute_VendorSellPrices["hateforge belt"] = 10967
CraftRoute_VendorSellPrices["hateforge boots"] = 15745
CraftRoute_VendorSellPrices["hateforge cuirass"] = 26288
CraftRoute_VendorSellPrices["hateforge helmet"] = 19407
CraftRoute_VendorSellPrices["hateforge leggings"] = 26270
CraftRoute_VendorSellPrices["healing potion"] = 75
CraftRoute_VendorSellPrices["heart of the sea"] = 3077
CraftRoute_VendorSellPrices["heavy blasting powder"] = 150
CraftRoute_VendorSellPrices["heavy bronze mace"] = 2741
CraftRoute_VendorSellPrices["heavy copper broadsword"] = 1498
CraftRoute_VendorSellPrices["heavy copper maul"] = 595
CraftRoute_VendorSellPrices["heavy dynamite"] = 350
CraftRoute_VendorSellPrices["heavy earthen gloves"] = 978
CraftRoute_VendorSellPrices["heavy gemstone cluster"] = 80
CraftRoute_VendorSellPrices["heavy grinding stone"] = 100
CraftRoute_VendorSellPrices["heavy gritted paper"] = 100
CraftRoute_VendorSellPrices["heavy kodo stew"] = 300
CraftRoute_VendorSellPrices["heavy leather ammo pouch"] = 500
CraftRoute_VendorSellPrices["heavy leather ball"] = 0
CraftRoute_VendorSellPrices["heavy leather"] = 150
CraftRoute_VendorSellPrices["heavy mithril axe"] = 12520
CraftRoute_VendorSellPrices["heavy mithril boots"] = 5769
CraftRoute_VendorSellPrices["heavy mithril gauntlet"] = 2476
CraftRoute_VendorSellPrices["heavy mithril helm"] = 5790
CraftRoute_VendorSellPrices["heavy mithril pants"] = 5387
CraftRoute_VendorSellPrices["heavy mithril shoulder"] = 3701
CraftRoute_VendorSellPrices["heavy scorpid belt"] = 10375
CraftRoute_VendorSellPrices["heavy scorpid helm"] = 18230
CraftRoute_VendorSellPrices["heavy scorpid leggings"] = 21760
CraftRoute_VendorSellPrices["heavy scorpid shoulders"] = 20261
CraftRoute_VendorSellPrices["heavy scorpid vest"] = 16604
CraftRoute_VendorSellPrices["heavy sharpening stone"] = 40
CraftRoute_VendorSellPrices["heavy timbermaw belt"] = 13291
CraftRoute_VendorSellPrices["heavy weightstone"] = 40
CraftRoute_VendorSellPrices["heavy woolen cloak"] = 475
CraftRoute_VendorSellPrices["heavy woolen gloves"] = 180
CraftRoute_VendorSellPrices["heavy woolen pants"] = 743
CraftRoute_VendorSellPrices["hi-explosive bomb"] = 750
CraftRoute_VendorSellPrices["hi-impact mithril slugs"] = 2
CraftRoute_VendorSellPrices["holy protection potion"] = 62
CraftRoute_VendorSellPrices["hot lion chops"] = 125
CraftRoute_VendorSellPrices["hot smoked bass"] = 10
CraftRoute_VendorSellPrices["hot wolf ribs"] = 312
CraftRoute_VendorSellPrices["huge thorium battleaxe"] = 39949
CraftRoute_VendorSellPrices["hydrathorn bracers"] = 256
CraftRoute_VendorSellPrices["hypertech battery pack"] = 0
CraftRoute_VendorSellPrices["ice deflector"] = 175
CraftRoute_VendorSellPrices["illuminated gemstone"] = 1000
CraftRoute_VendorSellPrices["imperial plate belt"] = 5533
CraftRoute_VendorSellPrices["imperial plate boots"] = 12062
CraftRoute_VendorSellPrices["imperial plate bracers"] = 6044
CraftRoute_VendorSellPrices["imperial plate gauntlets"] = 5326
CraftRoute_VendorSellPrices["imperial plate helm"] = 12106
CraftRoute_VendorSellPrices["imperial plate shoulders"] = 8646
CraftRoute_VendorSellPrices["inlaid copper ring"] = 114
CraftRoute_VendorSellPrices["inlaid thorium hammer"] = 38871
CraftRoute_VendorSellPrices["invisibility potion"] = 500
CraftRoute_VendorSellPrices["iridescent hammer"] = 3693
CraftRoute_VendorSellPrices["iron buckle"] = 100
CraftRoute_VendorSellPrices["iron counterweight"] = 500
CraftRoute_VendorSellPrices["iron grenade"] = 500
CraftRoute_VendorSellPrices["iron shield spike"] = 250
CraftRoute_VendorSellPrices["iron strut"] = 400
CraftRoute_VendorSellPrices["ironbloom ring"] = 2231
CraftRoute_VendorSellPrices["ironforge breastplate"] = 871
CraftRoute_VendorSellPrices["ironforge chain"] = 496
CraftRoute_VendorSellPrices["ironforge gauntlets"] = 1145
CraftRoute_VendorSellPrices["ironsun citrine ring"] = 2500
CraftRoute_VendorSellPrices["jade harmony circlet"] = 2250
CraftRoute_VendorSellPrices["jade serpentblade"] = 7304
CraftRoute_VendorSellPrices["jungle stew"] = 300
CraftRoute_VendorSellPrices["kodoheart necklace"] = 1016
CraftRoute_VendorSellPrices["large blue rocket cluster"] = 50
CraftRoute_VendorSellPrices["large blue rocket"] = 12
CraftRoute_VendorSellPrices["large copper bomb"] = 175
CraftRoute_VendorSellPrices["large green rocket cluster"] = 50
CraftRoute_VendorSellPrices["large green rocket"] = 12
CraftRoute_VendorSellPrices["large red rocket cluster"] = 50
CraftRoute_VendorSellPrices["large red rocket"] = 12
CraftRoute_VendorSellPrices["large seaforium charge"] = 900
CraftRoute_VendorSellPrices["lavender mageweave shirt"] = 3000
CraftRoute_VendorSellPrices["lavish gemmed necklace"] = 206
CraftRoute_VendorSellPrices["lean venison"] = 95
CraftRoute_VendorSellPrices["lesser fortification ring"] = 138
CraftRoute_VendorSellPrices["lesser healing potion"] = 25
CraftRoute_VendorSellPrices["lesser invisibility potion"] = 100
CraftRoute_VendorSellPrices["lesser mana potion"] = 30
CraftRoute_VendorSellPrices["lesser stoneshield potion"] = 375
CraftRoute_VendorSellPrices["lifelike mechanical toad"] = 2500
CraftRoute_VendorSellPrices["light armor kit"] = 15
CraftRoute_VendorSellPrices["light leather pants"] = 599
CraftRoute_VendorSellPrices["light leather quiver"] = 25
CraftRoute_VendorSellPrices["limited invulnerability potion"] = 30
CraftRoute_VendorSellPrices["linen belt"] = 22
CraftRoute_VendorSellPrices["linen boots"] = 87
CraftRoute_VendorSellPrices["living action potion"] = 600
CraftRoute_VendorSellPrices["lobster stew"] = 14
CraftRoute_VendorSellPrices["long silken cloak"] = 2496
CraftRoute_VendorSellPrices["longjaw mud snapper"] = 1
CraftRoute_VendorSellPrices["lordaeron breastplate"] = 871
CraftRoute_VendorSellPrices["mageblood potion"] = 1000
CraftRoute_VendorSellPrices["mageweave bag"] = 2500
CraftRoute_VendorSellPrices["magic resistance potion"] = 20
CraftRoute_VendorSellPrices["major healing potion"] = 1000
CraftRoute_VendorSellPrices["major mana potion"] = 1500
CraftRoute_VendorSellPrices["major recombobulator"] = 600
CraftRoute_VendorSellPrices["major troll's blood potion"] = 1000
CraftRoute_VendorSellPrices["malachite ring"] = 92
CraftRoute_VendorSellPrices["mana binding signet"] = 8305
CraftRoute_VendorSellPrices["mana potion"] = 120
CraftRoute_VendorSellPrices["marine root"] = 1050
CraftRoute_VendorSellPrices["marine's demise"] = 925
CraftRoute_VendorSellPrices["massive iron axe"] = 11248
CraftRoute_VendorSellPrices["master engineer's goggles"] = 11739
CraftRoute_VendorSellPrices["masterwork target dummy"] = 10000
CraftRoute_VendorSellPrices["mechanical dragonling"] = 6000
CraftRoute_VendorSellPrices["mechanical repair kit"] = 250
CraftRoute_VendorSellPrices["medallion of flame"] = 336
CraftRoute_VendorSellPrices["medium armor kit"] = 200
CraftRoute_VendorSellPrices["medium leather"] = 50
CraftRoute_VendorSellPrices["mightfish steak"] = 18
CraftRoute_VendorSellPrices["mighty iron hammer"] = 4552
CraftRoute_VendorSellPrices["mighty rage potion"] = 0
CraftRoute_VendorSellPrices["mighty troll's blood potion"] = 105
CraftRoute_VendorSellPrices["minor healing potion"] = 5
CraftRoute_VendorSellPrices["minor magic resistance potion"] = 20
CraftRoute_VendorSellPrices["minor mana potion"] = 10
CraftRoute_VendorSellPrices["minor recombobulator"] = 600
CraftRoute_VendorSellPrices["minor rejuvenation potion"] = 15
CraftRoute_VendorSellPrices["minor trollblood ring"] = 138
CraftRoute_VendorSellPrices["mistwood tiara"] = 525
CraftRoute_VendorSellPrices["mithril blackstone necklace"] = 4628
CraftRoute_VendorSellPrices["mithril blunderbuss"] = 8958
CraftRoute_VendorSellPrices["mithril casing"] = 1000
CraftRoute_VendorSellPrices["mithril coif"] = 7955
CraftRoute_VendorSellPrices["mithril frag bomb"] = 750
CraftRoute_VendorSellPrices["mithril gyro-shot"] = 5
CraftRoute_VendorSellPrices["mithril head trout"] = 6
CraftRoute_VendorSellPrices["mithril heavy-bore rifle"] = 11369
CraftRoute_VendorSellPrices["mithril mechanical dragonling"] = 6000
CraftRoute_VendorSellPrices["mithril scale bracers"] = 4103
CraftRoute_VendorSellPrices["mithril scale gloves"] = 4447
CraftRoute_VendorSellPrices["mithril scale shoulders"] = 10365
CraftRoute_VendorSellPrices["mithril shield spike"] = 250
CraftRoute_VendorSellPrices["mithril spurs"] = 250
CraftRoute_VendorSellPrices["mithril tube"] = 750
CraftRoute_VendorSellPrices["monastery emberbrace"] = 650
CraftRoute_VendorSellPrices["monster omelet"] = 300
CraftRoute_VendorSellPrices["mooncloth"] = 4000
CraftRoute_VendorSellPrices["moonlight staff"] = 2068
CraftRoute_VendorSellPrices["moonsight rifle"] = 3183
CraftRoute_VendorSellPrices["moonsteel broadsword"] = 10153
CraftRoute_VendorSellPrices["murloc scale bracers"] = 2316
CraftRoute_VendorSellPrices["murloc scale breastplate"] = 601
CraftRoute_VendorSellPrices["nature protection potion"] = 300
CraftRoute_VendorSellPrices["netherbane rod"] = 500
CraftRoute_VendorSellPrices["nightfin soup"] = 12
CraftRoute_VendorSellPrices["nightscape boots"] = 7158
CraftRoute_VendorSellPrices["nightscape headband"] = 4495
CraftRoute_VendorSellPrices["nightscape pants"] = 8708
CraftRoute_VendorSellPrices["nightscape shoulders"] = 4782
CraftRoute_VendorSellPrices["nightscape tunic"] = 5971
CraftRoute_VendorSellPrices["nimble leather gloves"] = 588
CraftRoute_VendorSellPrices["obsidian brooch"] = 3000
CraftRoute_VendorSellPrices["ocean's gaze"] = 2018
CraftRoute_VendorSellPrices["ocean's wrath"] = 350
CraftRoute_VendorSellPrices["ogre bone band"] = 1000
CraftRoute_VendorSellPrices["oil of immolation"] = 200
CraftRoute_VendorSellPrices["opal guided bangles"] = 6308
CraftRoute_VendorSellPrices["opaline illuminator"] = 16250
CraftRoute_VendorSellPrices["orange mageweave shirt"] = 1500
CraftRoute_VendorSellPrices["orange martial shirt"] = 1500
CraftRoute_VendorSellPrices["orb of clairvoyance"] = 15625
CraftRoute_VendorSellPrices["orcish war leggings"] = 7739
CraftRoute_VendorSellPrices["ornament of restraint"] = 8300
CraftRoute_VendorSellPrices["ornate mithril boots"] = 6739
CraftRoute_VendorSellPrices["ornate mithril bracelets"] = 3285
CraftRoute_VendorSellPrices["ornate mithril breastplate"] = 8368
CraftRoute_VendorSellPrices["ornate mithril crown"] = 3108
CraftRoute_VendorSellPrices["ornate mithril gloves"] = 2987
CraftRoute_VendorSellPrices["ornate mithril helm"] = 6763
CraftRoute_VendorSellPrices["ornate mithril pants"] = 5952
CraftRoute_VendorSellPrices["ornate mithril scepter"] = 4964
CraftRoute_VendorSellPrices["ornate spyglass"] = 600
CraftRoute_VendorSellPrices["ornate thorium handaxe"] = 33079
CraftRoute_VendorSellPrices["patterned bronze bracers"] = 807
CraftRoute_VendorSellPrices["pearl-clasped cloak"] = 370
CraftRoute_VendorSellPrices["pearl-handled dagger"] = 2107
CraftRoute_VendorSellPrices["pendant of arcane radiance"] = 5617
CraftRoute_VendorSellPrices["pendant of midnight"] = 1206
CraftRoute_VendorSellPrices["philosopher's stone"] = 250
CraftRoute_VendorSellPrices["phoenix gloves"] = 526
CraftRoute_VendorSellPrices["phoenix pants"] = 1076
CraftRoute_VendorSellPrices["pillager's amice"] = 10402
CraftRoute_VendorSellPrices["pillager's grips"] = 6287
CraftRoute_VendorSellPrices["pillager's hood"] = 9671
CraftRoute_VendorSellPrices["pillager's pantaloons"] = 12864
CraftRoute_VendorSellPrices["pillager's robe"] = 16204
CraftRoute_VendorSellPrices["pillager's shoes"] = 8898
CraftRoute_VendorSellPrices["pink mageweave shirt"] = 3000
CraftRoute_VendorSellPrices["poached sunscale salmon"] = 12
CraftRoute_VendorSellPrices["polished steel boots"] = 3937
CraftRoute_VendorSellPrices["portable bronze mortar"] = 2000
CraftRoute_VendorSellPrices["powerful citrine pendant"] = 3375
CraftRoute_VendorSellPrices["powerful seaforium charge"] = 3000
CraftRoute_VendorSellPrices["practice lock"] = 12
CraftRoute_VendorSellPrices["prism amulet"] = 12775
CraftRoute_VendorSellPrices["pristine crystal gemstone"] = 600
CraftRoute_VendorSellPrices["pure shining moonstone"] = 1000
CraftRoute_VendorSellPrices["purification potion"] = 750
CraftRoute_VendorSellPrices["quartz halo"] = 2000
CraftRoute_VendorSellPrices["quickdraw quiver"] = 1000
CraftRoute_VendorSellPrices["quicksilver whirl"] = 6000
CraftRoute_VendorSellPrices["radiant belt"] = 7595
CraftRoute_VendorSellPrices["radiant boots"] = 16421
CraftRoute_VendorSellPrices["radiant breastplate"] = 17003
CraftRoute_VendorSellPrices["radiant circlet"] = 17034
CraftRoute_VendorSellPrices["radiant ember gemstone"] = 1000
CraftRoute_VendorSellPrices["radiant gloves"] = 10242
CraftRoute_VendorSellPrices["radiant thorium twilight"] = 3025
CraftRoute_VendorSellPrices["rage potion"] = 30
CraftRoute_VendorSellPrices["rainbow fin albacore"] = 3
CraftRoute_VendorSellPrices["raptor hide belt"] = 1553
CraftRoute_VendorSellPrices["raptor hide harness"] = 3096
CraftRoute_VendorSellPrices["red firework"] = 0
CraftRoute_VendorSellPrices["red linen robe"] = 99
CraftRoute_VendorSellPrices["red linen shirt"] = 25
CraftRoute_VendorSellPrices["red linen vest"] = 160
CraftRoute_VendorSellPrices["red mageweave bag"] = 2500
CraftRoute_VendorSellPrices["red mageweave gloves"] = 3275
CraftRoute_VendorSellPrices["red mageweave headband"] = 6075
CraftRoute_VendorSellPrices["red mageweave shoulders"] = 5391
CraftRoute_VendorSellPrices["red mageweave vest"] = 5799
CraftRoute_VendorSellPrices["red rocket cluster"] = 25
CraftRoute_VendorSellPrices["red woolen bag"] = 700
CraftRoute_VendorSellPrices["red woolen boots"] = 416
CraftRoute_VendorSellPrices["regal twilight staff"] = 28837
CraftRoute_VendorSellPrices["reinforced linen cape"] = 67
CraftRoute_VendorSellPrices["reinforced woolen shoulders"] = 896
CraftRoute_VendorSellPrices["restorative potion"] = 200
CraftRoute_VendorSellPrices["rich purple silk shirt"] = 1500
CraftRoute_VendorSellPrices["ring of midnight"] = 809
CraftRoute_VendorSellPrices["ring of purified silver"] = 837
CraftRoute_VendorSellPrices["ring of the turtle"] = 1501
CraftRoute_VendorSellPrices["roast raptor"] = 300
CraftRoute_VendorSellPrices["roasted boar meat"] = 6
CraftRoute_VendorSellPrices["robe of power"] = 4700
CraftRoute_VendorSellPrices["robe of winter night"] = 17025
CraftRoute_VendorSellPrices["robes of arcana"] = 1807
CraftRoute_VendorSellPrices["rockscale cod"] = 6
CraftRoute_VendorSellPrices["rose colored goggles"] = 5169
CraftRoute_VendorSellPrices["rough blasting powder"] = 4
CraftRoute_VendorSellPrices["rough boomstick"] = 187
CraftRoute_VendorSellPrices["rough bronze boots"] = 469
CraftRoute_VendorSellPrices["rough bronze bracers"] = 629
CraftRoute_VendorSellPrices["rough bronze cuirass"] = 1312
CraftRoute_VendorSellPrices["rough bronze leggings"] = 962
CraftRoute_VendorSellPrices["rough bronze ring"] = 50
CraftRoute_VendorSellPrices["rough bronze shoulders"] = 319
CraftRoute_VendorSellPrices["rough copper bomb"] = 60
CraftRoute_VendorSellPrices["rough copper ring"] = 5
CraftRoute_VendorSellPrices["rough copper vest"] = 32
CraftRoute_VendorSellPrices["rough dynamite"] = 30
CraftRoute_VendorSellPrices["rough gemstone cluster"] = 20
CraftRoute_VendorSellPrices["rough gold ring"] = 600
CraftRoute_VendorSellPrices["rough grinding stone"] = 5
CraftRoute_VendorSellPrices["rough gritted paper"] = 5
CraftRoute_VendorSellPrices["rough iron ring"] = 200
CraftRoute_VendorSellPrices["rough mithril ring"] = 400
CraftRoute_VendorSellPrices["rough sharpening stone"] = 3
CraftRoute_VendorSellPrices["rough silver ring"] = 100
CraftRoute_VendorSellPrices["rough thorium ring"] = 600
CraftRoute_VendorSellPrices["rough truesilver ring"] = 1250
CraftRoute_VendorSellPrices["rough weightstone"] = 3
CraftRoute_VendorSellPrices["royal gemstone staff"] = 15836
CraftRoute_VendorSellPrices["rugged leather pants"] = 162
CraftRoute_VendorSellPrices["rune edge"] = 35338
CraftRoute_VendorSellPrices["runebound amulet"] = 13750
CraftRoute_VendorSellPrices["runecloth bag"] = 5000
CraftRoute_VendorSellPrices["runecloth belt"] = 5112
CraftRoute_VendorSellPrices["runecloth cloak"] = 8741
CraftRoute_VendorSellPrices["runecloth gloves"] = 6617
CraftRoute_VendorSellPrices["runecloth headband"] = 11358
CraftRoute_VendorSellPrices["runecloth pants"] = 13555
CraftRoute_VendorSellPrices["runecloth robe"] = 10917
CraftRoute_VendorSellPrices["runed copper belt"] = 312
CraftRoute_VendorSellPrices["runed copper bracers"] = 373
CraftRoute_VendorSellPrices["runed copper breastplate"] = 630
CraftRoute_VendorSellPrices["runed copper gauntlets"] = 182
CraftRoute_VendorSellPrices["runed copper pants"] = 299
CraftRoute_VendorSellPrices["runed mithril hammer"] = 12576
CraftRoute_VendorSellPrices["runed truesilver ring"] = 2644
CraftRoute_VendorSellPrices["runic leather belt"] = 8368
CraftRoute_VendorSellPrices["runic leather bracers"] = 7656
CraftRoute_VendorSellPrices["runic leather headband"] = 14155
CraftRoute_VendorSellPrices["runic leather pants"] = 20885
CraftRoute_VendorSellPrices["sagefish delight"] = 125
CraftRoute_VendorSellPrices["salt shaker"] = 7500
CraftRoute_VendorSellPrices["savory deviate delight"] = 5
CraftRoute_VendorSellPrices["searing golden blade"] = 10395
CraftRoute_VendorSellPrices["serpent's coil staff"] = 1250
CraftRoute_VendorSellPrices["shadow crescent axe"] = 14221
CraftRoute_VendorSellPrices["shadow goggles"] = 722
CraftRoute_VendorSellPrices["shadow hood"] = 1999
CraftRoute_VendorSellPrices["shadow oil"] = 150
CraftRoute_VendorSellPrices["shadow protection potion"] = 100
CraftRoute_VendorSellPrices["shadoweave boots"] = 6030
CraftRoute_VendorSellPrices["shadoweave pants"] = 5276
CraftRoute_VendorSellPrices["shadoweave robe"] = 5738
CraftRoute_VendorSellPrices["shadoweave shoulders"] = 5938
CraftRoute_VendorSellPrices["shadowfall jewel"] = 300
CraftRoute_VendorSellPrices["shadowforged eye"] = 275
CraftRoute_VendorSellPrices["shadowgem band"] = 505
CraftRoute_VendorSellPrices["shadowmoon orb"] = 300
CraftRoute_VendorSellPrices["shadowskin gloves"] = 3321
CraftRoute_VendorSellPrices["shimmering aqua gemstone"] = 1000
CraftRoute_VendorSellPrices["shimmering bronze ring"] = 442
CraftRoute_VendorSellPrices["shimmering gold necklace"] = 4403
CraftRoute_VendorSellPrices["shimmering moonstone tablet"] = 2687
CraftRoute_VendorSellPrices["shining copper cuffs"] = 205
CraftRoute_VendorSellPrices["shining silver breastplate"] = 2935
CraftRoute_VendorSellPrices["silk headband"] = 1257
CraftRoute_VendorSellPrices["silver contact"] = 25
CraftRoute_VendorSellPrices["silver medallion"] = 500
CraftRoute_VendorSellPrices["silver rod"] = 125
CraftRoute_VendorSellPrices["silver skeleton key"] = 50
CraftRoute_VendorSellPrices["silver-plated shotgun"] = 2357
CraftRoute_VendorSellPrices["silvered bronze boots"] = 1317
CraftRoute_VendorSellPrices["silvered bronze breastplate"] = 1831
CraftRoute_VendorSellPrices["silvered bronze gauntlets"] = 965
CraftRoute_VendorSellPrices["silvered bronze leggings"] = 2842
CraftRoute_VendorSellPrices["silvered bronze shoulders"] = 1284
CraftRoute_VendorSellPrices["simple black dress"] = 4499
CraftRoute_VendorSellPrices["simple dress"] = 59
CraftRoute_VendorSellPrices["simple kilt"] = 164
CraftRoute_VendorSellPrices["simple linen boots"] = 32
CraftRoute_VendorSellPrices["simple linen pants"] = 23
CraftRoute_VendorSellPrices["skyfire jewel"] = 3125
CraftRoute_VendorSellPrices["slitherskin mackerel"] = 1
CraftRoute_VendorSellPrices["small blue rocket"] = 6
CraftRoute_VendorSellPrices["small bronze bomb"] = 200
CraftRoute_VendorSellPrices["small green rocket"] = 6
CraftRoute_VendorSellPrices["small leather ammo pouch"] = 25
CraftRoute_VendorSellPrices["small pearl ring"] = 151
CraftRoute_VendorSellPrices["small pearlstone staff"] = 904
CraftRoute_VendorSellPrices["small red rocket"] = 6
CraftRoute_VendorSellPrices["small seaforium charge"] = 150
CraftRoute_VendorSellPrices["small silk pack"] = 2000
CraftRoute_VendorSellPrices["smoked bear meat"] = 6
CraftRoute_VendorSellPrices["smoked sagefish"] = 40
CraftRoute_VendorSellPrices["smoldering brooch"] = 3250
CraftRoute_VendorSellPrices["snake burst firework"] = 1
CraftRoute_VendorSellPrices["sniper scope"] = 2500
CraftRoute_VendorSellPrices["snowmaster 9000"] = 7500
CraftRoute_VendorSellPrices["soft-soled linen boots"] = 237
CraftRoute_VendorSellPrices["softglow ring"] = 168
CraftRoute_VendorSellPrices["solid blasting powder"] = 250
CraftRoute_VendorSellPrices["solid dynamite"] = 350
CraftRoute_VendorSellPrices["solid gemstone cluster"] = 120
CraftRoute_VendorSellPrices["solid grinding stone"] = 200
CraftRoute_VendorSellPrices["solid gritted paper"] = 200
CraftRoute_VendorSellPrices["solid iron maul"] = 6258
CraftRoute_VendorSellPrices["solid sharpening stone"] = 40
CraftRoute_VendorSellPrices["solid weightstone"] = 40
CraftRoute_VendorSellPrices["soothing turtle bisque"] = 300
CraftRoute_VendorSellPrices["spectre shade ring"] = 750
CraftRoute_VendorSellPrices["spellpower goggles xtreme plus"] = 9002
CraftRoute_VendorSellPrices["spellpower goggles xtreme"] = 4088
CraftRoute_VendorSellPrices["spellweaver pendant"] = 5011
CraftRoute_VendorSellPrices["spellweaver rod"] = 10000
CraftRoute_VendorSellPrices["sphinx's wisdom staff"] = 1925
CraftRoute_VendorSellPrices["spiced chili crab"] = 300
CraftRoute_VendorSellPrices["spider sausage"] = 300
CraftRoute_VendorSellPrices["spider silk slippers"] = 1120
CraftRoute_VendorSellPrices["spidersilk boots"] = 979
CraftRoute_VendorSellPrices["spotted yellowtail"] = 5
CraftRoute_VendorSellPrices["staff of blossomed jade"] = 3750
CraftRoute_VendorSellPrices["staff of gallitrea"] = 11538
CraftRoute_VendorSellPrices["standard scope"] = 600
CraftRoute_VendorSellPrices["starforge amulet"] = 10500
CraftRoute_VendorSellPrices["steel breastplate"] = 6488
CraftRoute_VendorSellPrices["steel plate armor"] = 9416
CraftRoute_VendorSellPrices["steel plate barbute"] = 9131
CraftRoute_VendorSellPrices["steel plate boots"] = 6301
CraftRoute_VendorSellPrices["steel plate gauntlets"] = 4164
CraftRoute_VendorSellPrices["steel plate helm"] = 3964
CraftRoute_VendorSellPrices["steel plate legguards"] = 9604
CraftRoute_VendorSellPrices["steel plate pauldrons"] = 7345
CraftRoute_VendorSellPrices["steel weapon chain"] = 1500
CraftRoute_VendorSellPrices["stonescale oil"] = 125
CraftRoute_VendorSellPrices["stormcloud sigil"] = 6712
CraftRoute_VendorSellPrices["strong troll's blood potion"] = 40
CraftRoute_VendorSellPrices["sturdy copper ring"] = 92
CraftRoute_VendorSellPrices["stylish blue shirt"] = 250
CraftRoute_VendorSellPrices["stylish green shirt"] = 250
CraftRoute_VendorSellPrices["stylish red shirt"] = 250
CraftRoute_VendorSellPrices["succulent pork ribs"] = 75
CraftRoute_VendorSellPrices["sunburst tiara"] = 8750
CraftRoute_VendorSellPrices["superior healing potion"] = 250
CraftRoute_VendorSellPrices["superior mana potion"] = 400
CraftRoute_VendorSellPrices["swift boots"] = 4253
CraftRoute_VendorSellPrices["swiftness potion"] = 25
CraftRoute_VendorSellPrices["swim speed potion"] = 35
CraftRoute_VendorSellPrices["talisman of stone"] = 327
CraftRoute_VendorSellPrices["target dummy"] = 75
CraftRoute_VendorSellPrices["tender wolf steak"] = 300
CraftRoute_VendorSellPrices["the golden goblet"] = 3000
CraftRoute_VendorSellPrices["the king's conviction"] = 275
CraftRoute_VendorSellPrices["thick armor kit"] = 1000
CraftRoute_VendorSellPrices["thick leather ammo pouch"] = 1000
CraftRoute_VendorSellPrices["thick leather"] = 300
CraftRoute_VendorSellPrices["thick murloc armor"] = 3211
CraftRoute_VendorSellPrices["thick war axe"] = 937
CraftRoute_VendorSellPrices["thistle tea"] = 30
CraftRoute_VendorSellPrices["thorium armor"] = 9239
CraftRoute_VendorSellPrices["thorium belt"] = 4636
CraftRoute_VendorSellPrices["thorium boots"] = 10336
CraftRoute_VendorSellPrices["thorium bracers"] = 4998
CraftRoute_VendorSellPrices["thorium greatsword"] = 33621
CraftRoute_VendorSellPrices["thorium grenade"] = 1500
CraftRoute_VendorSellPrices["thorium helm"] = 10372
CraftRoute_VendorSellPrices["thorium rifle"] = 19739
CraftRoute_VendorSellPrices["thorium shells"] = 10
CraftRoute_VendorSellPrices["thorium shield spike"] = 500
CraftRoute_VendorSellPrices["thorium spurs"] = 1000
CraftRoute_VendorSellPrices["thorium tube"] = 3750
CraftRoute_VendorSellPrices["thorium widget"] = 2500
CraftRoute_VendorSellPrices["tigercrest ring"] = 133
CraftRoute_VendorSellPrices["topaz studded ring"] = 173
CraftRoute_VendorSellPrices["totem of self preservation"] = 800
CraftRoute_VendorSellPrices["tough scorpid bracers"] = 4346
CraftRoute_VendorSellPrices["tough scorpid breastplate"] = 8628
CraftRoute_VendorSellPrices["tough scorpid gloves"] = 4676
CraftRoute_VendorSellPrices["tough scorpid helm"] = 10272
CraftRoute_VendorSellPrices["toughened leather armor"] = 1356
CraftRoute_VendorSellPrices["tranquil mechanical yeti"] = 1250
CraftRoute_VendorSellPrices["truesilver bar"] = 1250
CraftRoute_VendorSellPrices["truesilver rod"] = 1000
CraftRoute_VendorSellPrices["truesilver skeleton key"] = 625
CraftRoute_VendorSellPrices["truesilver transformer"] = 3000
CraftRoute_VendorSellPrices["turtle scale breastplate"] = 7567
CraftRoute_VendorSellPrices["turtle scale gloves"] = 3477
CraftRoute_VendorSellPrices["turtle scale leggings"] = 10952
CraftRoute_VendorSellPrices["tuxedo shirt"] = 2000
CraftRoute_VendorSellPrices["undermine clam chowder"] = 100
CraftRoute_VendorSellPrices["unstable mining dynamite"] = 75
CraftRoute_VendorSellPrices["unstable trigger"] = 1000
CraftRoute_VendorSellPrices["vitriol brooch"] = 3250
CraftRoute_VendorSellPrices["voice amplification modulator"] = 5930
CraftRoute_VendorSellPrices["voidheart charm"] = 15250
CraftRoute_VendorSellPrices["volcanic hammer"] = 39255
CraftRoute_VendorSellPrices["weak troll's blood potion"] = 10
CraftRoute_VendorSellPrices["whirring bronze gizmo"] = 115
CraftRoute_VendorSellPrices["white bandit mask"] = 4365
CraftRoute_VendorSellPrices["white leather jerkin"] = 150
CraftRoute_VendorSellPrices["white linen robe"] = 99
CraftRoute_VendorSellPrices["white linen shirt"] = 75
CraftRoute_VendorSellPrices["white wedding dress"] = 1767
CraftRoute_VendorSellPrices["white woolen dress"] = 466
CraftRoute_VendorSellPrices["wicked leather armor"] = 22732
CraftRoute_VendorSellPrices["wicked leather bracers"] = 7311
CraftRoute_VendorSellPrices["wicked leather gauntlets"] = 6872
CraftRoute_VendorSellPrices["wicked mithril blade"] = 15891
CraftRoute_VendorSellPrices["wild leather boots"] = 8150
CraftRoute_VendorSellPrices["wild leather cloak"] = 9017
CraftRoute_VendorSellPrices["wild leather helmet"] = 6230
CraftRoute_VendorSellPrices["wild leather leggings"] = 11585
CraftRoute_VendorSellPrices["wild leather shoulders"] = 5537
CraftRoute_VendorSellPrices["wild leather vest"] = 8002
CraftRoute_VendorSellPrices["wildvine potion"] = 250
CraftRoute_VendorSellPrices["wisdom of the timbermaw"] = 9232
CraftRoute_VendorSellPrices["woolen bag"] = 300
CraftRoute_VendorSellPrices["woolen boots"] = 359
CraftRoute_VendorSellPrices["woolen cape"] = 253
