-- Survival recipe data, sourced from Turtle WoW's own Atlas-CFM addon
-- data files (CFMLoot/Data/Tables/Crafting.lua + Spells.lua), same source
-- as Jewelcrafting's original data. Reagent names resolved via the addon's
-- own item database cross-referenced against octowow.st; 3 items needed
-- disambiguation before use (see DEVNOTES): item #12361 was ambiguously
-- labeled "Pure Moonstone" (collided with Jewelcrafting's #55251) and is
-- really Blue Sapphire; "Striped Melon Seeds" covered two different real
-- items (#51708 kept the name, #51712 is really Juicy Watermelon).
--
-- learnCost is a banded placeholder (200/500/2700 by skill tier, same
-- convention used everywhere else) -- learn-source data (trainer/vendor/AH)
-- hasn't been done for this profession yet. No recipe here has a
-- scrollName yet for that reason.
--
-- Starfeather Arrows (both variant recipes, spell 30061 and 30067) removed
-- entirely -- they shared an identical name, which would have collided in
-- CraftRoute's name-keyed recipe lookup, and the second variant strictly
-- needed a superset of the first's reagents for the identical output, so
-- it would never have been chosen anyway.
--
-- 15 recipes with orange>=300 were removed entirely (out of CraftRoute's
-- 1-300 scope, same policy as Jewelcrafting) -- not excluded=true, just not here.
CraftRoute_Data = CraftRoute_Data or {}
CraftRoute_Data["survival"] = {
  {name="Dim Torch", orange=1, yellow=30, green=45, grey=60, learnCost=200, learnCostConfidence="estimated", reagents={{name="Unlit Poor Torch", qty=1}}},
  {name="Bundle of Simple Sticks", orange=5, yellow=10, green=12, grey=15, learnCost=200, learnCostConfidence="estimated", reagents={{name="Simple Wood", qty=2}}},
  {name="Driftwood Fishing Pole", orange=10, yellow=40, green=55, grey=70, learnCost=200, learnCostConfidence="estimated", reagents={{name="Coarse Thread", qty=2}, {name="Rugged String", qty=1}, {name="Simple Wood", qty=2}}},
  {name="Survivalist's Skinning Knife", orange=10, yellow=30, green=45, grey=60, learnCost=200, learnCostConfidence="estimated", reagents={{name="Rough Stone", qty=2}, {name="Coarse Thread", qty=1}, {name="Light Leather", qty=1}}},
  {name="Crude Hatchet", orange=15, yellow=25, green=35, grey=45, learnCost=200, learnCostConfidence="estimated", reagents={{name="Simple Wood", qty=1}, {name="Copper Bar", qty=3}}},
  {name="Crude Hunting Bow", orange=15, yellow=25, green=35, grey=45, learnCost=200, learnCostConfidence="estimated", reagents={{name="Simple Wood", qty=3}, {name="Springy Rope", qty=2}}},
  {name="Crude Machete", orange=15, yellow=25, green=35, grey=45, learnCost=200, learnCostConfidence="estimated", reagents={{name="Simple Wood", qty=1}, {name="Copper Bar", qty=3}}},
  {name="Crude Walking Stick", orange=15, yellow=25, green=35, grey=45, learnCost=200, learnCostConfidence="estimated", reagents={{name="Simple Wood", qty=4}}},
  {name="Copper Lantern", orange=20, yellow=40, green=50, grey=60, learnCost=200, learnCostConfidence="estimated", reagents={{name="Dim Torch", qty=1}, {name="Copper Bar", qty=3}}},
  {name="Simple Slingshot", orange=30, yellow=50, green=60, grey=70, learnCost=200, learnCostConfidence="estimated", reagents={{name="Striped Melon Seeds", qty=4}, {name="Bundle of Simple Sticks", qty=2}, {name="Springy Rope", qty=1}}},
  {name="Makeshift Rations Bag", orange=40, yellow=60, green=70, grey=80, learnCost=200, learnCostConfidence="estimated", reagents={{name="Light Leather", qty=4}, {name="Coarse Thread", qty=6}, {name="Cured Light Hide", qty=1}, {name="Salt", qty=4}}},
  {name="Simple Herbalist's Backpack", orange=40, yellow=60, green=70, grey=80, learnCost=200, learnCostConfidence="estimated", excluded=true, excludeFromMakeVsBuy=true, reagents={{name="Light Leather", qty=6}, {name="Coarse Thread", qty=4}, {name="Cured Light Hide", qty=2}, {name="Peacebloom", qty=12}}},
  {name="Weak Healing Salve", orange=50, yellow=70, green=80, grey=90, learnCost=200, learnCostConfidence="estimated", reagents={{name="Refreshing Spring Water", qty=1}, {name="Remedy Herbs", qty=2}, {name="Simple Leaves", qty=1}}},
  {name="Makeshift Knife", orange=60, yellow=80, green=90, grey=100, learnCost=200, learnCostConfidence="estimated", reagents={{name="Simple Wood", qty=1}, {name="Copper Bar", qty=3}, {name="Light Leather", qty=2}}},
  {name="Gardening Gloves", orange=65, yellow=85, green=95, grey=105, learnCost=200, learnCostConfidence="estimated", reagents={{name="Light Leather", qty=4}, {name="Coarse Thread", qty=2}, {name="Peacebloom", qty=6}}},
  {name="Crude Fishing Rod", orange=70, yellow=90, green=100, grey=110, learnCost=200, learnCostConfidence="estimated", reagents={{name="Simple Wood", qty=8}, {name="Fine Thread", qty=1}}},
  {name="Traveler's Tent", orange=50, yellow=100, green=125, grey=150, learnCost=200, learnCostConfidence="estimated", reagents={{name="Simple Wood", qty=5}, {name="Linen Cloth", qty=10}, {name="Sturdy Rope", qty=1}}},
  {name="Fishing Boat", orange=75, yellow=125, green=150, grey=175, learnCost=200, learnCostConfidence="estimated", reagents={{name="Simple Wood", qty=20}, {name="Handful of Copper Bolts", qty=10}, {name="Fish Oil", qty=2}}},
  {name="Hunting Spear", orange=90, yellow=110, green=120, grey=130, learnCost=200, learnCostConfidence="estimated", reagents={{name="Bronze Bar", qty=8}, {name="Light Leather", qty=4}, {name="Fine Thread", qty=2}, {name="Simple Wood", qty=12}}},
  {name="Gardening Broom", orange=95, yellow=115, green=125, grey=135, learnCost=200, learnCostConfidence="estimated", reagents={{name="Simple Wood", qty=6}, {name="Bundle of Simple Sticks", qty=8}, {name="Fine Thread", qty=1}, {name="Medium Leather", qty=1}}},
  {name="Healing Salve", orange=100, yellow=120, green=130, grey=140, learnCost=500, learnCostConfidence="estimated", reagents={{name="Simple Leaves", qty=4}, {name="Remedy Herbs", qty=2}, {name="Spider Ichor", qty=1}}},
  {name="Oakwood Bow", orange=100, yellow=120, green=130, grey=140, learnCost=500, learnCostConfidence="estimated", reagents={{name="Simple Wood", qty=12}, {name="Bleach", qty=2}, {name="Springy Rope", qty=2}, {name="Medium Leather", qty=1}}},
  {name="Simple Fishing Lure", orange=100, yellow=120, green=130, grey=140, learnCost=500, learnCostConfidence="estimated", reagents={{name="Clam Meat", qty=1}, {name="Remedy Herbs", qty=1}}},
  {name="Fishing Bag", orange=105, yellow=125, green=135, grey=145, learnCost=500, learnCostConfidence="estimated", excluded=true, excludeFromMakeVsBuy=true, reagents={{name="Medium Leather", qty=8}, {name="Fine Thread", qty=4}, {name="Cured Light Hide", qty=4}, {name="Salt", qty=6}}},
  {name="Skinner's Pack", orange=110, yellow=130, green=140, grey=150, learnCost=500, learnCostConfidence="estimated", excluded=true, excludeFromMakeVsBuy=true, reagents={{name="Medium Leather", qty=6}, {name="Fine Thread", qty=2}, {name="Cured Light Hide", qty=4}, {name="Skinning Knife", qty=1}}},
  {name="Gardening Pitchfork", orange=120, yellow=140, green=150, grey=160, learnCost=500, learnCostConfidence="estimated", reagents={{name="Bronze Bar", qty=10}, {name="Simple Wood", qty=10}, {name="Medium Leather", qty=4}}},
  {name="Murloc's Flippers", orange=120, yellow=150, green=162, grey=175, learnCost=500, learnCostConfidence="estimated", reagents={{name="Thick Murloc Scale", qty=16}, {name="Heavy Leather", qty=8}, {name="Heavy Silken Thread", qty=2}, {name="Blackmouth Oil", qty=3}, {name="Swim Speed Potion", qty=1}}},
  {name="Blackmouth Fishing Trap", orange=125, yellow=145, green=155, grey=165, learnCost=500, learnCostConfidence="estimated", reagents={{name="Bundle of Bright Wood Sticks", qty=2}, {name="Simple Fishing Lure", qty=1}, {name="Sturdy Net", qty=1}}},
  {name="Bundle of Bright Wood Sticks", orange=125, yellow=135, green=140, grey=145, learnCost=500, learnCostConfidence="estimated", reagents={{name="Bright Wood", qty=3}}},
  {name="Murloc Scale Coat", orange=125, yellow=145, green=155, grey=165, learnCost=500, learnCostConfidence="estimated", reagents={{name="Medium Leather", qty=6}, {name="Fine Thread", qty=2}, {name="Slimy Murloc Scale", qty=10}, {name="Swim Speed Potion", qty=2}}},
  {name="Sturdy Blade", orange=130, yellow=150, green=160, grey=170, learnCost=500, learnCostConfidence="estimated", reagents={{name="Bright Wood", qty=2}, {name="Medium Leather", qty=1}, {name="Bronze Bar", qty=8}, {name="Moss Agate", qty=1}, {name="Coarse Grinding Stone", qty=2}}},
  {name="Sturdy Cane", orange=130, yellow=150, green=160, grey=170, learnCost=500, learnCostConfidence="estimated", reagents={{name="Bright Wood", qty=12}, {name="Medium Leather", qty=2}, {name="Fine Thread", qty=1}}},
  {name="Sturdy Knife", orange=130, yellow=150, green=160, grey=170, learnCost=500, learnCostConfidence="estimated", reagents={{name="Bright Wood", qty=2}, {name="Medium Leather", qty=2}, {name="Bronze Bar", qty=6}, {name="Moss Agate", qty=1}, {name="Coarse Gritted Paper", qty=2}}},
  {name="Sturdy Net", orange=130, yellow=130, green=135, grey=140, learnCost=500, learnCostConfidence="estimated", reagents={{name="Sturdy Rope", qty=4}}},
  {name="Reliable Fishing Rod", orange=135, yellow=155, green=165, grey=175, learnCost=500, learnCostConfidence="estimated", reagents={{name="Bright Wood", qty=6}, {name="Fine Thread", qty=1}, {name="Bronze Bar", qty=2}}},
  {name="Hat of the Junior Chef", orange=140, yellow=160, green=170, grey=180, learnCost=500, learnCostConfidence="estimated", reagents={{name="Bolt of Silk Cloth", qty=6}, {name="Bleach", qty=8}, {name="Silken Thread", qty=4}, {name="Hot Spices", qty=5}, {name="Soothing Spices", qty=5}, {name="Spider's Silk", qty=5}}},
  {name="Rugged Mining Sack", orange=140, yellow=160, green=170, grey=180, learnCost=500, learnCostConfidence="estimated", reagents={{name="Heavy Leather", qty=8}, {name="Cured Medium Hide", qty=3}, {name="Yellow Dye", qty=2}, {name="Silken Thread", qty=4}, {name="Silk Cloth", qty=14}}},
  {name="Throwable Net", orange=140, yellow=160, green=170, grey=180, learnCost=500, learnCostConfidence="estimated", reagents={{name="Sturdy Net", qty=1}, {name="Coarse Stone", qty=4}}},
  {name="Bright Wood Arrows", orange=145, yellow=165, green=175, grey=185, learnCost=500, learnCostConfidence="estimated", reagents={{name="Bundle of Bright Wood Sticks", qty=1}, {name="Long Tail Feather", qty=1}, {name="Iron Bar", qty=1}}},
  {name="Treasure Compass", orange=145, yellow=165, green=175, grey=185, learnCost=500, learnCostConfidence="estimated", reagents={{name="Silver Contact", qty=4}, {name="Bronze Framework", qty=6}, {name="Handful of Copper Bolts", qty=20}, {name="Jade", qty=2}, {name="Whirring Bronze Gizmo", qty=6}}},
  {name="Potent Healing Salve", orange=150, yellow=170, green=180, grey=190, learnCost=500, learnCostConfidence="estimated", reagents={{name="Remedy Herbs", qty=4}, {name="Bright Leaves", qty=3}, {name="Refreshing Spring Water", qty=1}}},
  {name="Spicy Fishing Lure", orange=150, yellow=170, green=180, grey=190, learnCost=500, learnCostConfidence="estimated", reagents={{name="Tangy Clam Meat", qty=1}, {name="Hot Spices", qty=1}}},
  {name="Studded Rations Bag", orange=150, yellow=170, green=180, grey=190, learnCost=500, learnCostConfidence="estimated", reagents={{name="Heavy Leather", qty=8}, {name="Cured Medium Hide", qty=3}, {name="Yellow Dye", qty=2}, {name="Silken Thread", qty=4}, {name="Blackmouth Oil", qty=6}, {name="Salt", qty=8}}},
  {name="Iron Lantern", orange=90, yellow=90, green=90, grey=90, learnCost=200, learnCostConfidence="estimated", reagents={{name="Iron Bar", qty=2}, {name="Flask of Oil", qty=4}, {name="Wool Cloth", qty=5}}},
  {name="Cleaning Cloth", orange=100, yellow=150, green=175, grey=200, learnCost=500, learnCostConfidence="estimated", reagents={{name="Silk Cloth", qty=2}, {name="Volatile Rum", qty=1}}},
  {name="Slowing Bolas", orange=155, yellow=175, green=185, grey=195, learnCost=500, learnCostConfidence="estimated", reagents={{name="Heavy Stone", qty=3}, {name="Sturdy Rope", qty=2}}},
  {name="Snap Trap", orange=160, yellow=180, green=190, grey=200, learnCost=500, learnCostConfidence="estimated", reagents={{name="Iron Strut", qty=4}, {name="Handful of Copper Bolts", qty=8}}},
  {name="Edged Machete", orange=165, yellow=185, green=195, grey=205, learnCost=500, learnCostConfidence="estimated", reagents={{name="Iron Bar", qty=8}, {name="Heavy Leather", qty=2}, {name="Sturdy Rope", qty=1}, {name="Bright Wood", qty=1}}},
  {name="Iron Spear", orange=165, yellow=185, green=195, grey=205, learnCost=500, learnCostConfidence="estimated", reagents={{name="Iron Bar", qty=8}, {name="Heavy Grinding Stone", qty=2}, {name="Sturdy Rope", qty=1}, {name="Heavy Leather", qty=2}}},
  {name="Reinforced Fishing Rod", orange=170, yellow=190, green=200, grey=210, learnCost=500, learnCostConfidence="estimated", reagents={{name="Iron Bar", qty=2}, {name="Shade Wood", qty=8}, {name="Springy Rope", qty=1}, {name="Handful of Copper Bolts", qty=10}}},
  {name="Bundle of Shade Wood Sticks", orange=175, yellow=185, green=190, grey=195, learnCost=500, learnCostConfidence="estimated", reagents={{name="Shade Wood", qty=4}}},
  {name="Firefin Fishing Trap", orange=175, yellow=195, green=205, grey=215, learnCost=500, learnCostConfidence="estimated", reagents={{name="Bundle of Shade Wood Sticks", qty=2}, {name="Spicy Fishing Lure", qty=1}, {name="Sturdy Net", qty=1}}},
  {name="Water Trudgers", orange=175, yellow=195, green=205, grey=215, learnCost=500, learnCostConfidence="estimated", reagents={{name="Heavy Leather", qty=12}, {name="Shiny Fish Scales", qty=20}, {name="Gray Dye", qty=2}, {name="Iridescent Pearl", qty=4}}},
  {name="Sharpened Herb Sickle", orange=180, yellow=200, green=210, grey=220, learnCost=500, learnCostConfidence="estimated", reagents={{name="Iron Bar", qty=2}, {name="Gold Bar", qty=1}, {name="Shade Wood", qty=1}, {name="Heavy Leather", qty=2}, {name="Handful of Copper Bolts", qty=4}}},
  {name="Lined Wintercloak", orange=185, yellow=205, green=215, grey=225, learnCost=500, learnCostConfidence="estimated", excluded=true, excludeFromMakeVsBuy=true, reagents={{name="Cured Heavy Hide", qty=2}, {name="Heavy Leather", qty=8}, {name="Gray Dye", qty=2}, {name="Silk Cloth", qty=6}, {name="Silken Thread", qty=4}}},
  {name="Sleek Pinewood Bow", orange=190, yellow=210, green=220, grey=230, learnCost=500, learnCostConfidence="estimated", excluded=true, excludeFromMakeVsBuy=true, reagents={{name="Shade Wood", qty=8}, {name="Springy Rope", qty=1}, {name="Gold Bar", qty=2}, {name="Long Tail Feather", qty=6}}},
  {name="Jungle Remedy", orange=195, yellow=215, green=225, grey=235, learnCost=500, learnCostConfidence="estimated", scrollName="Outline: Jungle Remedy", requiresScan=true, reagents={{name="Remedy Herbs", qty=4}, {name="Shade Leaves", qty=2}, {name="Junglevine Wine", qty=1}}},
  {name="Savory Fishing Lure", orange=200, yellow=220, green=230, grey=240, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Zesty Clam Meat", qty=1}, {name="Soothing Spices", qty=2}}},
  {name="Superior Healing Salve", orange=200, yellow=220, green=230, grey=240, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Remedy Herbs", qty=6}, {name="Liferoot", qty=1}, {name="Shade Leaves", qty=4}}},
  {name="Nutritious Rations", orange=205, yellow=225, green=235, grey=245, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Juicy Watermelon", qty=2}, {name="Sour Mountain Berry", qty=2}, {name="Plump Country Pumpkin", qty=2}}},
  {name="Shade Wood Arrows", orange=205, yellow=225, green=235, grey=245, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Bundle of Shade Wood Sticks", qty=1}, {name="Delicate Feather", qty=1}, {name="Mithril Bar", qty=1}}},
  {name="Hiking Staff", orange=215, yellow=235, green=245, grey=255, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Shade Wood", qty=10}, {name="Sturdy Rope", qty=4}, {name="Solid Grinding Stone", qty=2}}},
  {name="Tree Hatchet", orange=215, yellow=235, green=245, grey=255, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Mithril Bar", qty=10}, {name="Solid Grinding Stone", qty=4}, {name="Solid Gritted Paper", qty=2}, {name="Bundle of Shade Wood Sticks", qty=1}}},
  {name="Vine Cutter", orange=215, yellow=235, green=245, grey=255, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Mithril Bar", qty=10}, {name="Solid Grinding Stone", qty=2}, {name="Thick Leather", qty=4}, {name="Bundle of Shade Wood Sticks", qty=1}}},
  {name="Bundle of Tropical Sticks", orange=225, yellow=235, green=240, grey=245, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Tropical Wood", qty=5}}},
  {name="Repaired Electro-Lantern", orange=120, yellow=120, green=135, grey=150, learnCost=500, learnCostConfidence="estimated", excluded=true, excludeFromMakeVsBuy=true, reagents={{name="Broken Electro-lantern", qty=5}, {name="Mithril Casing", qty=1}, {name="Handful of Copper Bolts", qty=1}, {name="Whirring Bronze Gizmo", qty=1}, {name="Silver Contact", qty=2}, {name="Gold Power Core", qty=2}}},
  {name="Sunshade Hat", orange=235, yellow=255, green=265, grey=275, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Thick Leather", qty=12}, {name="Fire Protection Potion", qty=2}, {name="Elemental Fire", qty=4}, {name="Deeprock Salt", qty=6}, {name="Small Flame Sac", qty=5}}},
  {name="Thick Rations Bag", orange=235, yellow=255, green=265, grey=275, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Thick Leather", qty=12}, {name="Cured Thick Hide", qty=2}, {name="Heavy Silken Thread", qty=4}, {name="Mageweave Cloth", qty=10}, {name="Deeprock Salt", qty=5}}},
  {name="Aromatic Berries", orange=240, yellow=260, green=270, grey=280, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Sweet Mountain Berry", qty=1}, {name="Remedy Herbs", qty=1}, {name="Soothing Spices", qty=2}}},
  {name="Spiced Berries", orange=240, yellow=260, green=270, grey=280, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Sour Mountain Berry", qty=1}, {name="Remedy Herbs", qty=1}, {name="Hot Spices", qty=2}}},
  {name="Warped Recurve Bow", orange=240, yellow=260, green=270, grey=280, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Tropical Wood", qty=10}, {name="Thick Leather", qty=4}, {name="Springy Rope", qty=2}, {name="Vibrant Plume", qty=6}, {name="Breath of Wind", qty=4}}},
  {name="Advanced Camouflage", orange=245, yellow=265, green=275, grey=285, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Un'Goro Soil", qty=2}, {name="Bundle of Tropical Sticks", qty=2}, {name="Tropical Leaves", qty=10}}},
  {name="Emergency Parachute", orange=250, yellow=270, green=280, grey=290, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Sturdy Rope", qty=4}, {name="Runecloth", qty=5}, {name="Sturdy Net", qty=1}}},
  {name="Premium Fishing Lure", orange=250, yellow=270, green=280, grey=290, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Zesty Clam Meat", qty=2}, {name="Molasses Firewater", qty=1}}},
  {name="Stabilizing Healing Salve", orange=250, yellow=270, green=280, grey=290, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Remedy Herbs", qty=8}, {name="Purple Lotus", qty=1}, {name="Tropical Leaves", qty=4}}},
  {name="Smooth Ironfeather Arrows", orange=255, yellow=275, green=285, grey=295, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Bundle of Tropical Sticks", qty=1}, {name="Ironfeather", qty=1}, {name="Thorium Bar", qty=1}}},
  {name="Heavy Duty Machete", orange=260, yellow=280, green=285, grey=290, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Thorium Bar", qty=6}, {name="Rugged Leather", qty=4}, {name="Dense Grinding Stone", qty=2}}},
  {name="Thorium Edged Machete", orange=260, yellow=280, green=285, grey=290, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Thorium Bar", qty=10}, {name="Rugged Leather", qty=4}, {name="Dense Grinding Stone", qty=2}, {name="Dense Gritted Paper", qty=2}, {name="Star Ruby", qty=1}}},
  {name="Thorium Spear", orange=265, yellow=285, green=295, grey=305, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Thorium Bar", qty=4}, {name="Rugged Leather", qty=4}, {name="Tropical Wood", qty=6}, {name="Dense Gritted Paper", qty=2}}},
  {name="Bundle of Star Wood Sticks", orange=270, yellow=275, green=280, grey=285, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Star Wood", qty=5}}},
  {name="Razor-sharp Skinning Knife", orange=270, yellow=290, green=300, grey=310, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Skinning Knife", qty=1}, {name="Dense Sharpening Stone", qty=4}, {name="Enchanted Thorium Bar", qty=8}, {name="Star Ruby", qty=6}, {name="Elemental Fire", qty=8}, {name="Essence of Fire", qty=4}}},
  {name="Mastercraft Fishing Rod", orange=275, yellow=295, green=305, grey=315, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Thorium Bar", qty=8}, {name="Rugged Leather", qty=4}, {name="Tropical Wood", qty=10}, {name="Springy Rope", qty=2}, {name="Thorium Tube", qty=4}, {name="Essence of Water", qty=4}}},
  {name="Stonescale Fishing Trap", orange=275, yellow=295, green=305, grey=315, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Bundle of Star Wood Sticks", qty=2}, {name="Premium Fishing Lure", qty=1}, {name="Sturdy Net", qty=2}}},
  {name="Miner's Rucksack", orange=280, yellow=300, green=310, grey=320, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Rugged Leather", qty=24}, {name="Cured Thick Hide", qty=3}, {name="Bundle of Star Wood Sticks", qty=10}, {name="Mining Pick", qty=1}, {name="Iron Buckle", qty=4}, {name="Rune Thread", qty=6}}},
  {name="Herbalist's Knapsack", orange=285, yellow=305, green=315, grey=325, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Rugged Leather", qty=22}, {name="Cured Thick Hide", qty=4}, {name="Bundle of Star Wood Sticks", qty=10}, {name="Gardening Gloves", qty=1}, {name="Iron Buckle", qty=4}, {name="Rune Thread", qty=4}}},
  {name="Skinner's Carryall", orange=285, yellow=305, green=315, grey=325, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Rugged Leather", qty=28}, {name="Enchanted Leather", qty=6}, {name="Cured Rugged Hide", qty=2}, {name="Skinner’s Pack", qty=1}, {name="Iron Buckle", qty=4}, {name="Rune Thread", qty=6}}},
  {name="Fisherman's Backpack", orange=285, yellow=305, green=315, grey=325, learnCost=0, learnCostConfidence="confirmed", questObtained=true, reagents={{name="Rugged Leather", qty=20}, {name="Cured Thick Hide", qty=6}, {name="Bundle of Star Wood Sticks", qty=10}, {name="Mastercraft Fishing Rod", qty=1}, {name="Iron Buckle", qty=4}, {name="Rune Thread", qty=6}}},
  {name="Cooling Rations Bag", orange=290, yellow=310, green=320, grey=330, learnCost=2700, learnCostConfidence="estimated", reagents={{name="Rugged Leather", qty=18}, {name="Enchanted Leather", qty=8}, {name="Cured Rugged Hide", qty=2}, {name="Essence of Water", qty=4}, {name="Iron Buckle", qty=4}, {name="Rune Thread", qty=6}}},
  {name="Oil-Powered Cooker", orange=295, yellow=315, green=325, grey=335, learnCost=0, learnCostConfidence="confirmed", questObtained=true, reagents={{name="Mithril Casing", qty=8}, {name="Thorium Widget", qty=6}, {name="Gold Power Core", qty=6}, {name="Flask of Oil", qty=10}, {name="Essence of Fire", qty=2}, {name="Enchanted Thorium Bar", qty=4}}},
}
