-- Vendor prices for materials and recipe scrolls (copper, per unit).
CraftRoute_VendorPrices = CraftRoute_VendorPrices or {}
CraftRoute_VendorPrices["black dye"] = 1000
CraftRoute_VendorPrices["blacksmith hammer"] = 18
CraftRoute_VendorPrices["blank parchment"] = 50
CraftRoute_VendorPrices["bleach"] = 25
CraftRoute_VendorPrices["blue dye"] = 5000
CraftRoute_VendorPrices["coal"] = 500
CraftRoute_VendorPrices["coarse thread"] = 10
CraftRoute_VendorPrices["copper rod"] = 124
CraftRoute_VendorPrices["crystal vial"] = 500
CraftRoute_VendorPrices["elemental flux"] = 150000
CraftRoute_VendorPrices["empty vial"] = 4
CraftRoute_VendorPrices["engineer's ink"] = 1800
CraftRoute_VendorPrices["fine thread"] = 100
CraftRoute_VendorPrices["flint and tinder"] = 135
CraftRoute_VendorPrices["formula: enchant chest - minor mana"] = 300
CraftRoute_VendorPrices["formula: enchanted gemstone oil"] = 50000
CraftRoute_VendorPrices["formula: lesser wizard oil"] = 4000
CraftRoute_VendorPrices["formula: minor mana oil"] = 3000
CraftRoute_VendorPrices["formula: minor wizard oil"] = 500
CraftRoute_VendorPrices["formula: runed arcanite rod"] = 22000
CraftRoute_VendorPrices["gemstone oil"] = 2500
CraftRoute_VendorPrices["gray dye"] = 350
CraftRoute_VendorPrices["green dye"] = 100
CraftRoute_VendorPrices["heavy silken thread"] = 2000
CraftRoute_VendorPrices["heavy stock"] = 2000
CraftRoute_VendorPrices["holy candle"] = 700
CraftRoute_VendorPrices["hot spices"] = 40
CraftRoute_VendorPrices["ice cold milk"] = 25
CraftRoute_VendorPrices["imbued vial"] = 6000
CraftRoute_VendorPrices["jeweler's kit"] = 200
CraftRoute_VendorPrices["junglevine wine"] = 300
CraftRoute_VendorPrices["leaded vial"] = 40
CraftRoute_VendorPrices["mild spices"] = 2
CraftRoute_VendorPrices["mining pick"] = 81
CraftRoute_VendorPrices["molasses firewater"] = 1000
CraftRoute_VendorPrices["northwind flour"] = 400
CraftRoute_VendorPrices["orange dye"] = 1000
CraftRoute_VendorPrices["pattern: azure silk cloak"] = 1500
CraftRoute_VendorPrices["pattern: barbaric leggings"] = 650
CraftRoute_VendorPrices["pattern: black whelp cloak"] = 650
CraftRoute_VendorPrices["pattern: blue linen robe"] = 300
CraftRoute_VendorPrices["pattern: blue linen vest"] = 200
CraftRoute_VendorPrices["pattern: blue overalls"] = 400
CraftRoute_VendorPrices["pattern: bright yellow shirt"] = 800
CraftRoute_VendorPrices["pattern: crimson silk cloak"] = 1200
CraftRoute_VendorPrices["pattern: dark silk shirt"] = 1100
CraftRoute_VendorPrices["pattern: deviate scale cloak"] = 550
CraftRoute_VendorPrices["pattern: deviate scale gloves"] = 1500
CraftRoute_VendorPrices["pattern: earthen leather shoulders"] = 2000
CraftRoute_VendorPrices["pattern: enchanted mageweave pouch"] = 6000
CraftRoute_VendorPrices["pattern: gem-studded leather belt"] = 3000
CraftRoute_VendorPrices["pattern: green leather armor"] = 2000
CraftRoute_VendorPrices["pattern: lavender mageweave shirt"] = 4000
CraftRoute_VendorPrices["pattern: mooncloth"] = 20000
CraftRoute_VendorPrices["pattern: nightscape cloak"] = 5000
CraftRoute_VendorPrices["pattern: orange martial shirt"] = 3000
CraftRoute_VendorPrices["pattern: pink mageweave shirt"] = 4000
CraftRoute_VendorPrices["pattern: raptor hide belt"] = 2500
CraftRoute_VendorPrices["pattern: raptor hide harness"] = 2500
CraftRoute_VendorPrices["pattern: red whelp gloves"] = 1600
CraftRoute_VendorPrices["pattern: red woolen bag"] = 500
CraftRoute_VendorPrices["pattern: runecloth bag"] = 12000
CraftRoute_VendorPrices["pattern: runecloth gloves"] = 16000
CraftRoute_VendorPrices["pattern: runecloth robe"] = 12000
CraftRoute_VendorPrices["pattern: shadowskin gloves"] = 3500
CraftRoute_VendorPrices["pattern: tuxedo shirt"] = 4500
CraftRoute_VendorPrices["pattern: white wedding dress"] = 10000
CraftRoute_VendorPrices["pattern: wicked leather gauntlets"] = 12000
CraftRoute_VendorPrices["pink dye"] = 2500
CraftRoute_VendorPrices["plans: blue starfire"] = 9200
CraftRoute_VendorPrices["plans: dark iron signet ring"] = 22000
CraftRoute_VendorPrices["plans: goldcrest amulet"] = 8500
CraftRoute_VendorPrices["plans: golden scale coif"] = 4400
CraftRoute_VendorPrices["plans: hardened iron shortsword"] = 3000
CraftRoute_VendorPrices["plans: massive iron axe"] = 4400
CraftRoute_VendorPrices["plans: mithril scale bracers"] = 6000
CraftRoute_VendorPrices["plans: mithril scale gloves"] = 8000
CraftRoute_VendorPrices["plans: moonsteel broadsword"] = 4400
CraftRoute_VendorPrices["plans: ocean's wrath"] = 700
CraftRoute_VendorPrices["plans: orb of clairvoyance"] = 30000
CraftRoute_VendorPrices["plans: pure shining moonstone"] = 5000
CraftRoute_VendorPrices["plans: rough bronze bracers"] = 1200
CraftRoute_VendorPrices["plans: rune edge"] = 20000
CraftRoute_VendorPrices["plans: skyfire jewel"] = 11500
CraftRoute_VendorPrices["plans: solid iron maul"] = 3000
CraftRoute_VendorPrices["plans: thorium greatsword"] = 12000
CraftRoute_VendorPrices["polishing oil"] = 100
CraftRoute_VendorPrices["purple dye"] = 2500
CraftRoute_VendorPrices["recipe: ambersap glazed boar ribs"] = 2000
CraftRoute_VendorPrices["recipe: baked salmon"] = 20000
CraftRoute_VendorPrices["recipe: barbecued buzzard wing"] = 1000
CraftRoute_VendorPrices["recipe: big bear steak"] = 1600
CraftRoute_VendorPrices["recipe: brilliant smallfish"] = 40
CraftRoute_VendorPrices["recipe: bristle whisker catfish"] = 1200
CraftRoute_VendorPrices["recipe: carrion surprise"] = 5000
CraftRoute_VendorPrices["recipe: cooked glossy mightfish"] = 16000
CraftRoute_VendorPrices["recipe: curiously tasty omelet"] = 1600
CraftRoute_VendorPrices["recipe: dragonbreath chili"] = 7000
CraftRoute_VendorPrices["recipe: elixir of superior defense"] = 13000
CraftRoute_VendorPrices["recipe: filet of redgill"] = 16000
CraftRoute_VendorPrices["recipe: free action potion"] = 1800
CraftRoute_VendorPrices["recipe: ghost dye"] = 9000
CraftRoute_VendorPrices["recipe: giant clam scorcho"] = 5000
CraftRoute_VendorPrices["recipe: gilneas hot stew"] = 2500
CraftRoute_VendorPrices["recipe: grilled squid"] = 16000
CraftRoute_VendorPrices["recipe: heavy kodo stew"] = 7000
CraftRoute_VendorPrices["recipe: hot lion chops"] = 1800
CraftRoute_VendorPrices["recipe: hot smoked bass"] = 16000
CraftRoute_VendorPrices["recipe: hot wolf ribs"] = 5000
CraftRoute_VendorPrices["recipe: jungle stew"] = 3000
CraftRoute_VendorPrices["recipe: lean venison"] = 1200
CraftRoute_VendorPrices["recipe: lobster stew"] = 20000
CraftRoute_VendorPrices["recipe: longjaw mud snapper"] = 400
CraftRoute_VendorPrices["recipe: mightfish steak"] = 20000
CraftRoute_VendorPrices["recipe: mithril head trout"] = 2200
CraftRoute_VendorPrices["recipe: monster omelet"] = 12000
CraftRoute_VendorPrices["recipe: nightfin soup"] = 20000
CraftRoute_VendorPrices["recipe: poached sunscale salmon"] = 20000
CraftRoute_VendorPrices["recipe: rainbow fin albacore"] = 400
CraftRoute_VendorPrices["recipe: roast raptor"] = 5000
CraftRoute_VendorPrices["recipe: rockscale cod"] = 2200
CraftRoute_VendorPrices["recipe: sagefish delight"] = 5000
CraftRoute_VendorPrices["recipe: slitherskin mackerel"] = 40
CraftRoute_VendorPrices["recipe: smoked bear meat"] = 250
CraftRoute_VendorPrices["recipe: smoked sagefish"] = 500
CraftRoute_VendorPrices["recipe: spiced chili crab"] = 12000
CraftRoute_VendorPrices["recipe: spotted yellowtail"] = 16000
CraftRoute_VendorPrices["recipe: tender wolf steak"] = 12000
CraftRoute_VendorPrices["recipe: thistle tea"] = 200
CraftRoute_VendorPrices["recipe: undermine clam chowder"] = 3000
CraftRoute_VendorPrices["red dye"] = 50
CraftRoute_VendorPrices["refreshing spring water"] = 5
CraftRoute_VendorPrices["remedy herbs"] = 12
CraftRoute_VendorPrices["rugged string"] = 85
CraftRoute_VendorPrices["rune thread"] = 5000
CraftRoute_VendorPrices["salt"] = 50
CraftRoute_VendorPrices["schematic: accurate scope"] = 2000
CraftRoute_VendorPrices["schematic: blue firework"] = 1800
CraftRoute_VendorPrices["schematic: deepdive helmet"] = 3600
CraftRoute_VendorPrices["schematic: delicate arcanite converter"] = 20000
CraftRoute_VendorPrices["schematic: gnomish universal remote"] = 1200
CraftRoute_VendorPrices["schematic: goblin jumper cables"] = 2000
CraftRoute_VendorPrices["schematic: green firework"] = 1800
CraftRoute_VendorPrices["schematic: gyrofreeze ice reflector"] = 12000
CraftRoute_VendorPrices["schematic: ice deflector"] = 1800
CraftRoute_VendorPrices["schematic: lovingly crafted boomstick"] = 1000
CraftRoute_VendorPrices["schematic: masterwork target dummy"] = 16000
CraftRoute_VendorPrices["schematic: mechanical dragonling"] = 10000
CraftRoute_VendorPrices["schematic: minor recombobulator"] = 1500
CraftRoute_VendorPrices["schematic: mithril mechanical dragonling"] = 4000
CraftRoute_VendorPrices["schematic: portable wormhole generator: stormwind"] = 1000
CraftRoute_VendorPrices["schematic: powerful seaforium charge"] = 16000
CraftRoute_VendorPrices["schematic: red firework"] = 1800
CraftRoute_VendorPrices["schematic: thorium grenade"] = 12000
CraftRoute_VendorPrices["schematic: thorium tube"] = 16000
CraftRoute_VendorPrices["schematic: thorium widget"] = 12000
CraftRoute_VendorPrices["schematic: truesilver transformer"] = 12000
CraftRoute_VendorPrices["shimmering oil"] = 500
CraftRoute_VendorPrices["shiny red apple"] = 25
CraftRoute_VendorPrices["silken thread"] = 500
CraftRoute_VendorPrices["skinning knife"] = 82
CraftRoute_VendorPrices["soothing spices"] = 160
CraftRoute_VendorPrices["springy rope"] = 85
CraftRoute_VendorPrices["strong flux"] = 2000
CraftRoute_VendorPrices["sturdy rope"] = 100
CraftRoute_VendorPrices["unlit poor torch"] = 10
CraftRoute_VendorPrices["weak flux"] = 100
CraftRoute_VendorPrices["whittle"] = 54
CraftRoute_VendorPrices["wooden stock"] = 200
CraftRoute_VendorPrices["yellow dye"] = 500
